# Generated by Django 5.2.3 on 2025-07-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_categoria_etiqueta_elementoinventario_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementoinventario',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='elementoinventario',
            name='lote',
            field=models.CharField(blank=True, help_text='Identificador de lote (opcional)', max_length=50, null=True),
        ),
    ]
