# Generated by Django 5.2.3 on 2025-07-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_elementoinventario_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcioncompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
