# Generated by Django 5.2.3 on 2025-07-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_recepcioncompra_precio_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='auditoria_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.auditoriainventario'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='origen',
            field=models.CharField(choices=[('compra', 'Compra'), ('solicitud', 'Solicitud de Material'), ('devolucion', 'Devolución'), ('transferencia', 'Transferencia'), ('ajuste_manual', 'Ajuste Manual'), ('auditoria', 'Auditoría'), ('sistema', 'Sistema')], default='sistema', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='recepcion_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.recepcioncompra'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='solicitud_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.solicitudmaterial'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_nuevo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('devolucion', 'Devolución'), ('ajuste', 'Ajuste'), ('auditoria', 'Ajuste por Auditoría')], max_length=20),
        ),
    ]
