# Generated by Django 5.2.3 on 2025-07-01 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_movimientoinventario_eliminado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriainventario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la configuración', max_length=100, unique=True)),
                ('valor', models.TextField(help_text='Valor de la configuración')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la configuración')),
                ('categoria', models.CharField(choices=[('inventario', 'Inventario'), ('alertas', 'Alertas'), ('seguridad', 'Seguridad'), ('general', 'General')], default='general', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la configuración está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
