# Generated by Django 5.2.3 on 2025-07-02 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_auditoriainventario_observaciones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=200)),
                ('cantidad_asignada', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_liberacion_estimada', models.DateField()),
                ('fecha_liberacion_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('en_uso', 'En Uso'), ('liberado', 'Liberado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='inventario.elementoinventario')),
            ],
            options={
                'verbose_name': 'Asignación de Recurso',
                'verbose_name_plural': 'Asignaciones de Recursos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
