# Generated by Django 5.2.3 on 2025-07-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_asignacionrecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionrecurso',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
